# Generated by Django 5.0.6 on 2025-09-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('buyer', 'Buyer')], default='buyer', max_length=20, verbose_name='Role')),
                ('id_photo', models.ImageField(blank=True, help_text="Upload a photo of your NIN slip, Passport, or Driver's License.", null=True, upload_to='ids/', verbose_name='ID Photo')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('match_notes', models.TextField(blank=True, help_text='Notes on why the user was approved or rejected.', verbose_name='Admin Verification Notes')),
                ('referral_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Referral Code')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Credits')),
                ('entrepreneur_level', models.PositiveIntegerField(default=1, verbose_name='Entrepreneur Level')),
                ('experience_points', models.PositiveIntegerField(default=0, verbose_name='Experience Points (XP)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
