# Generated by Django 5.0.6 on 2025-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_page_url',
            field=models.URLField(blank=True, help_text='Your Instagram, Facebook, or WhatsApp Business link.', max_length=500, null=True),
        ),
    ]
