# Generated by Django 5.0.6 on 2025-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_business_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
