# Generated by Django 5.0.6 on 2025-09-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_verified',
        ),
    ]
