# Generated by Django 5.0.6 on 2025-09-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_location_verified_profile_verified_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified_street_address',
        ),
    ]
