# Generated by Django 5.0.6 on 2025-10-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp Business'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary link used for verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.profile')),
            ],
            options={
                'ordering': ['-is_primary', 'platform'],
            },
        ),
    ]
