# Generated by Django 5.0.6 on 2025-10-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Certificate name (e.g., Plumbing Certification, Electrical Safety)', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Who issued this certificate', max_length=200)),
                ('issue_date', models.DateField(help_text='When was this certificate issued')),
                ('expiry_date', models.DateField(blank=True, help_text="Leave blank if it doesn't expire", null=True)),
                ('certificate_image', models.ImageField(help_text='Upload certificate image', upload_to='certificates/')),
                ('description', models.TextField(blank=True, help_text='Additional details about this certification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.profile')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
