# Generated by Django 5.0.6 on 2025-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('whatsapp', 'WhatsApp Business'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
    ]
