# Generated by Django 5.0.6 on 2025-10-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
