databases:
  - name: kiri-db
    databaseName: kiri
    user: kiri
    plan: free

services:
  - type: web
    name: kiri
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn kiriong.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kiri-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: RECAPTCHA_PUBLIC_KEY
        sync: false
      - key: RECAPTCHA_PRIVATE_KEY
        sync: false
