# Generated by Django 5.0.6 on 2025-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_service_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexNowSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'IndexNow Submission',
                'verbose_name_plural': 'IndexNow Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_submit_to_indexnow', models.BooleanField(default=True, help_text='Automatically submit new/updated content to IndexNow')),
                ('indexnow_key', models.CharField(blank=True, help_text='IndexNow API key (auto-generated if empty)', max_length=100)),
                ('last_sitemap_ping', models.DateTimeField(blank=True, help_text='Last time sitemap was pinged to search engines', null=True)),
                ('last_indexnow_submission', models.DateTimeField(blank=True, help_text='Last IndexNow submission time', null=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
