# Generated by Django 5.0.6 on 2025-09-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='entrepreneur',
            new_name='artisan',
        ),
    ]
