# Generated by Django 5.0.6 on 2025-09-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_entrepreneur_service_artisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
