# Generated by Django 5.0.6 on 2025-10-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_serviceimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
