# Generated by Django 5.0.6 on 2025-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GN', 'General'), ('TU', 'Tutorial'), ('ST', 'Story'), ('TP', 'Tips & Tricks'), ('NW', 'News')], default='GN', help_text='Select the category that best describes your post', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 characters). Leave blank to auto-generate.', max_length=160),
        ),
    ]
