# Generated by Django 5.0.6 on 2025-09-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Badge Title')),
                ('description', models.TextField(verbose_name='Badge Description')),
                ('icon_svg', models.TextField(help_text='Paste the SVG code for the badge icon here.', verbose_name='Icon SVG Code')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name="User's Goal")),
                ('generated_modules', models.JSONField(default=list, help_text='The raw AI-generated module structure.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Module Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academy.learningpathway')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Step Title')),
                ('content_url', models.URLField(blank=True, null=True, verbose_name='Content URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('step_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('task', 'Practical Task')], default='video', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='academy.pathwaymodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='academy.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
