# Generated by Django 5.0.6 on 2025-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulestep',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='modulestep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modulestep',
            name='step_type',
        ),
        migrations.AddField(
            model_name='learningpathway',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='modulestep',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Supplementary Video URL'),
        ),
        migrations.AddField(
            model_name='modulestep',
            name='written_content',
            field=models.TextField(blank=True, verbose_name='Original Written Content'),
        ),
    ]
