# Generated by Django 5.0.6 on 2025-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_modulestep_content_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathway',
            name='generated_modules',
        ),
        migrations.RemoveField(
            model_name='modulestep',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='modulestep',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='modulestep',
            name='written_content',
        ),
        migrations.AddField(
            model_name='pathwaymodule',
            name='content_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathwaymodule',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Supplementary Video URL'),
        ),
        migrations.AddField(
            model_name='pathwaymodule',
            name='written_content',
            field=models.TextField(blank=True, verbose_name='Original Written Content'),
        ),
    ]
