# Generated by Django 5.0.6 on 2025-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_learningpathway_generated_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwaymodule',
            name='youtube_search_query',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
