# Generated by Django 5.0.6 on 2025-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_pathwaymodule_youtube_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwaymodule',
            name='validation_question',
            field=models.TextField(blank=True),
        ),
    ]
