# Generated by Django 5.0.6 on 2025-09-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_pathwaymodule_validation_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathwaymodule',
            name='validation_question',
        ),
    ]
