# Generated by Django 5.0.6 on 2025-09-23 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='earned_at',
            new_name='awarded_at',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learningpathway',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningpathway',
            name='goal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learningpathway',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_pathways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='academy.badge'),
        ),
    ]
