# Generated by Django 5.0.6 on 2025-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathway',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
