# Generated by Django 5.0.6 on 2025-10-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_learningpathway_location'),
        ('marketplace', '0005_remove_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathway',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_pathways', to='marketplace.category'),
        ),
    ]
