# Generated by Django 5.0.6 on 2025-10-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_learningpathway_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaymodule',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Primary Video URL'),
        ),
        migrations.AlterField(
            model_name='pathwaymodule',
            name='written_content',
            field=models.TextField(blank=True, verbose_name='Written Content'),
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('ai_answer', models.TextField(blank=True, verbose_name='AI-Generated Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.pathwaymodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='Video Description')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academy.pathwaymodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
